### ISSUE TITLE
Update demo site

### ISSUE THREAD

**Issue by deining** [rvanhorn/hugo-dynamic-tabs#11]
Version 2 supports right-aligned tabs now (thanks for implementing!). You updated the sample in the `demo` folder, too, but the [demo site](https://hugo-dynamic-tabs.netlify.com/) that's mentioned in `README.md` does not reflect this. Were great if you could update the site, so that all users can admire your new feature 😉.

**Comment by rvanhorn** [comment]
Done. :)
