### ISSUE TITLE
Feature request: last tab aligned to right margin

### ISSUE THREAD

**Issue by deining** [rvanhorn/hugo-dynamic-tabs#6]
I just came across this great project and immediately liked it. I will certainly evaluate this for my purposes.

**Two suggestions and one feature request:**

* I would propose you add the URL of the demo site to the repo infos given on the right margin: 

<img src="https://user-images.githubusercontent.com/18169566/112393383-44918700-8cfb-11eb-90aa-61b79a55fee6.png" width="350">

This way it should be easier to grasp what the repo is about.

* I would propose you add `Bootstrap` or `Bootstrap 4` to the cloud tag to the repo info section illustrated above.

* From time to time, I do have the requirement of having the last tab aligned to the right margin. This [demo](https://www.codeply.com/v/ABXjRXqLBO) illustrates what I am talking about. This [site](https://www.codeply.com/go/hhV1aM49zz) has the implementation details with Bootstrap 4. Adding this feature to this project would add even more value to this project IMHO.

**Comment by rvanhorn** [comment]
Thanks for the suggestions, I've added the link and the tags. 

Adding a drop-down would be a bit more difficult and would require its own shortcode set. Its outside the scope of this project but you could probably copy the tabs/tab shortcode and modify them to generate the dropdown.

**Comment by deining** [comment]
> Thanks for the suggestions, I've added the link and the tags.

Great, thank you.

> Adding a drop-down would be a bit more difficult

Please note that this issue is **not** about adding a drop-down menu, it's about support for **right aligning** tabs.
Please have a look at this [demo](https://www.codeply.com/go/WtDULmFF9G/bootstrap-4-right-align-tabs) to get a full understanding if what I mean. As described there, right aligning tabs can be done by simply adding `ml-auto` class:  

`<li class="nav-item **ml-auto**"><a class="nav-link" data-toggle="tab" href="#tab22" role="tab">More</a></li>`

I think this is something that could be achieved quite easily and would be an enhancement to this project.

**Comment by rvanhorn** [comment]
Ah, I misread your initial post, my apologies.

I'll take a look later this week and see what I can do.

**Comment by rvanhorn** [comment]
Now available with V2.00.
