### ISSUE TITLE
Does not work with Boostrap 5?

### ISSUE THREAD

**Issue by Bojhan** [rvanhorn/hugo-dynamic-tabs#9]
It looks like this is broken with Bootstrap 5?

**Comment by rvanhorn** [comment]
Hello there!

Apologies for the late reply. I no longer use this plugin myself so I check it every couple of months and must have checked right before you created your issue. 

Taking a quick glance, it seems they completely changed how tabs work. I was working on refactoring the code, so I'll finish that and then create a new branch for Bootstrap 5. 

Give me a week or so. :)

**Comment by ElementalCrisis** [comment]
Bootstrap 5 version now available.
https://github.com/rvanhorn/hugo-dynamic-tabs/tree/bootstrap5

Please see the changelog as I've made quite a few changes.

**Comment by rvanhorn** [comment]
Bootstrap 5 version now available.
https://github.com/rvanhorn/hugo-dynamic-tabs/tree/bootstrap5

Please see the changelog as I've made quite a few changes.
